name: update-lives-list

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run iptv
        run: python ${{ github.workspace }}/iptv.py

        
      - name: 提交
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.NAME }}
          git add .
          git commit *.txt -m "The iptv.txt file has been generated on $(date +"%Y.%m.%d-%H%M")"
          git commit *.m3u -m "The iptv.m3u file has been generated on $(date +"%Y.%m.%d-%H%M")"
          #git pull --rebase
          git push -f
